name: Publish Client.AuthContext
on:
  push:
    tags:
      - 'Client.AuthContext/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Set env
      run: set RELEASE_VERSION=%GITHUB_REF:~30%
    - uses: actions/checkout@master
    - name: Add GPR source with credentials to NuGet.config
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO_OWNER: Totopolis
        GITHUB_SOURCE_NAME: GPR
      run: ./.github/workflows/AddSourceWithCredentialsToNuGetConfig -ConfigFile ./NuGet.Config -Source %GITHUB_SOURCE_NAME% -Username %GITHUB_REPO_OWNER% -Password %GITHUB_TOKEN%
    - run: dotnet pack ./src/Domain0.Client.AuthContext/Domain0.Client.AuthContext.csproj -c Release -o NuGetPackages /p:Version=%RELEASE_VERSION%
    - name: Push to feeds
      env:
        MYGET_SOURCE: https://www.myget.org/F/totopolis/api/v3/index.json
        GITHUB_SOURCE_NAME: GPR
      run: |
        dotnet nuget push ./NuGetPackages/Domain0.Client.AuthContext.%RELEASE_VERSION%.nupkg -k ${{ secrets.MYGET_APIKEY }} -s %MYGET_SOURCE%
        dotnet nuget push ./NuGetPackages/Domain0.Client.AuthContext.%RELEASE_VERSION%.nupkg -s %GITHUB_SOURCE_NAME%