name: Publish Api.Client
on:
  push:
    tags:
      - 'Api.Client/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:22})
    - uses: actions/checkout@master
    - name: Add GPR source with credentials to NuGet.config
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO_OWNER: Totopolis
        GITHUB_SOURCE_NAME: GPR
      run: ./.github/workflows/AddSourceWithCredentialsToNuGetConfig -ConfigFile ./NuGet.Config -Source $GITHUB_SOURCE_NAME -Username $GITHUB_REPO_OWNER -Password $GITHUB_TOKEN
    - run: dotnet pack ./src/Domain0.Api.Client/Domain0.Api.Client.csproj -c Release -o NuGetPackages /p:Version=$RELEASE_VERSION
    - name: Push to feeds
      env:
        MYGET_SOURCE: https://www.myget.org/F/totopolis/api/v3/index.json
        GITHUB_SOURCE_NAME: GPR
      run: |
        dotnet nuget push ./NuGetPackages/Domain0.Api.Client.$RELEASE_VERSION.nupkg -k ${{ secrets.MYGET_APIKEY }} -s $MYGET_SOURCE
        dotnet nuget push ./NuGetPackages/Domain0.Api.Client.$RELEASE_VERSION.nupkg -s $GITHUB_SOURCE_NAME